services:

  ibcmon:
    image: ibcmon:latest
    command: ["-config", "/app/config/config.toml"]
    container_name: ibcmon
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /home/user/config/config.toml:/app/config/config.toml
